### ISSUE TITLE
Issue Running automlst

### ISSUE THREAD

**Issue by SevanEsaian** [KatSteinke/automlst-simplified-wrapper#1]
Hello, 
I have installed automlst and I am trying to run it on some metagenome assembled genomes in the form of fasta files. All of these metagenomes are from different soil samples but the genomes themselves are the same species. I have approximately 50 metagenome assembled genomes of the same species across different field sites. 

The script I am using is the following: 
`python automlst.py indir /home/sevan/Metagenomes/Thiohalocapsa_PSB resultdir /home/sevan/MultipleSequenceAlignmentTest/Thiohalocapsa_PSB_automlst_output`

When I run this script, I get the following error: 
`automlst.py: error: unrecognized arguments: resultdir /home/sevan/MultipleSequenceAlignmentTest/Thiohalocapsa_PSB_automlst_output`

How can I resolve this error? I am confused as to why `resultdir `is an unrecognized argument. When I run python `automlst.py -h` , it tells me that resultdir is used for setting the output directory.

Thank you for your help.

**Comment by KatSteinke** [comment]
Hi!
Just a heads-up first of all, this isn't the official repository - you'll find that on Bitbucket [here](https://bitbucket.org/ziemertlab/automlst/src/master/). This fork isn't really maintained any longer. But I think I can see what's going on there anyway. `indir` and `resultdir` are positional arguments, so you don't need to specify the argument name beforehand - it'll take the first non-flag argument as the input directory and the second as the result directory. Try running 
```
python automlst.py /home/sevan/Metagenomes/Thiohalocapsa_PSB /home/sevan/MultipleSequenceAlignmentTest/Thiohalocapsa_PSB_automlst_output
```
If automlst still gives you trouble afterwards, though, you'll have to get in touch with the current maintainers on Bitbucket - I haven't been with that group for a good five years now. (I'd recommend getting their version of automlst too, it's gotten some updates since this one.)

**Comment by SevanEsaian** [comment]
Thanks so much. If I have further inquiries, I will post on bitbucket. 
All the best.
